@server = https://solid-space-waddle-767pjvqww4p2p7jv-8080.app.github.dev

###
GET {{server}}/api/alumnos/3

###
GET {{server}}/api/cursos

###
GET {{server}}/api/notas

###
GET {{server}}/api/cursos/3/todo

######################################

###
GET {{server}}/api/instrumentos/2
###
POST {{server}}/api/instrumentos
Content-Type: application/json

{"nombre": "Quena", "categoria": "Viento", "descripcion": "Como una flauta"}
###
GET {{server}}/api/musicos
###
POST {{server}}/api/musicos
Content-Type: application/json

{"nombre": "Joaquín"}
###
GET {{server}}/api/bandas
###
GET {{server}}/api/bandas/1
###
GET {{server}}/api/bandas/1/formacion
###
GET {{server}}/api/integrantes
